name: 🚀 Release

on:
  workflow_dispatch:

env:
  NODE_VERSION: 22
  PNPM_VERSION: 10

jobs:
  plugin:
    name: Release plugin
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Verify main branch
        run: |
          if [[ "${{ github.ref_name }}" != "main" ]]; then
            echo "Release can only be done on the main branch."
            exit 1
          fi

      - name: Checkout project
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Build package
        run: pnpm build

      - name: Sign package
        working-directory: dist
        run: |
          if [[ -z "${{ secrets.PRIVATE_KEY }}" ]]; then
            echo "Set an ed25519 key as PRIVATE_KEY in GitHub Action secret to sign."
          else
            echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
            openssl pkeyutl -sign -inkey private_key.pem -out plugin_package.zip.sig -rawin -in plugin_package.zip
            rm private_key.pem
          fi

      - name: Check version
        id: meta
        working-directory: dist
        run: |
          VERSION=$(unzip -p ./plugin_package.zip manifest.json | jq -r .version)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload plugin package
        uses: actions/upload-artifact@v5
        with:
          name: plugin_package
          path: |
            dist/plugin_package.zip
            dist/plugin_package.zip.sig
          if-no-files-found: error

  server:
    name: Release server
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: plugin

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/drop:latest
            ghcr.io/${{ github.repository_owner }}/drop:${{ needs.plugin.outputs.version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/drop:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/drop:buildcache,mode=max

  github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - plugin
      - server

    steps:
      - name: Download plugin package
        uses: actions/download-artifact@v6
        with:
          name: plugin_package
          path: dist

      - name: Create release
        uses: caido/action-release@v1
        with:
          tag: ${{ needs.plugin.outputs.version }}
          commit: ${{ github.sha }}
          body: 'Release ${{ needs.plugin.outputs.version }}'
          artifacts: 'dist/plugin_package.zip,dist/plugin_package.zip.sig'
          immutableCreate: true
